### ISSUE TITLE
/profession set errors

### ISSUE THREAD

**Issue by alyphen** [RP-Kit/RPKit#523]
```
[22:01:48 INFO]: Zarkaylia issued server command: /profession set Zarkaylia cook
[22:01:48 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'profession' in plugin rpk-professions-bukkit v2.0.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Paper-457]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-457]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2021) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1832) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1785) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1087) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-457]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalArgumentException: Field ("rpkit_professions"."rpkit_character_profession"."profession") is not contained in Row ("rpkit_professions"."rpkit_character_profession"."character_id")
        at com.rpkit.professions.bukkit.shadow.impl.org.jooq.impl.Tools.indexFail(Tools.java:1981) ~[?:?]
        at com.rpkit.professions.bukkit.shadow.impl.org.jooq.impl.AbstractRecord.get(AbstractRecord.java:265) ~[?:?]
        at com.rpkit.professions.bukkit.database.table.RPKCharacterProfessionTable.get(RPKCharacterProfessionTable.kt:69) ~[?:?]
        at com.rpkit.professions.bukkit.profession.RPKProfessionServiceImpl.getProfessions(RPKProfessionServiceImpl.kt:49) ~[?:?]
        at com.rpkit.professions.bukkit.command.profession.ProfessionSetCommand.onCommand(ProfessionSetCommand.kt:111) ~[?:?]
        at com.rpkit.professions.bukkit.command.profession.ProfessionCommand.onCommand(ProfessionCommand.kt:41) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-457]
        ... 19 more
```

**Comment by alyphen** [comment]
Fixed with async stuff for professions
